trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndDeploy
  steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'

  - script: |
      python -m pip install -r requirements.txt
    displayName: 'Install dependencies'

  - task: Docker@2
    inputs:
      containerRegistry: 'YourAzureContainerRegistry'
      repository: 'subtitle-translator'
      command: 'buildAndPush'
      Dockerfile: 'devops/Dockerfile'
      tags: latest
