# version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000" # Host:Container
    environment:
      NODE_ENV: development
      # For local testing, put a dummy key here. Remove for deployment!
      AZURE_TRANSLATOR_KEY: "your-dummy-key-for-local-dev"
    volumes:
      - ./backend:/app # Mounts local code for hot-reloading

  frontend:
    build: ./frontend
    ports:
      - "80:80" # Host:Container
    depends_on:
      - backend
    environment:
      REACT_APP_BACKEND_URL: http://localhost:3000 # Frontend uses this to talk to backend
    volumes:
      - ./frontend:/app # Mounts local code for hot-reloading
